This notebook will be used to take data and find the best way to summarize and visualize before performing inferential analysis.

In [52]:
import pandas as pd
import numpy as np
import math

In [2]:
"""" This module contains all the functions used in the main.py file.  It takes in a
    list of products and creates dataframes of each, with the name as the key and daily
    price information as the value.  These functions also put the data into clean
    format in order to then insert both the product symbols and the price data into
    a SQLite3 database.
"""

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import datetime
import quandl
import sqlite3

def create_df_crypto(symbol, curr='USD', limit=2000):
    ''' This function takes in a symbol of a cryptocurrency to be
        used with the Cryptocompare API, and returns a formatted dataframe
        for later processing.

        Args: symbol - cryptocurrency symbol
              curr - currency to report in (default USD)
              limit - max number of data points (default 2500)

        Return: df - dataframe of daily price info for symbol
    '''
    # Set url and params for the call to Cryptocompare API
    url = 'https://min-api.cryptocompare.com/data/histoday'
    params = {'fsym': symbol, 'tsym': curr, 'limit': limit}

    # Call API for symbol and put data into pandas dataframe
    response = requests.get(url, params=params)
    data = response.json()['Data']
    df = pd.DataFrame(data)

    # Add date column and set to index
    df['Date'] =[datetime.date.fromtimestamp(d) for d in df.time]
    df = df[['open', 'high', 'low', 'close', 'volumeto', 'Date']]
    df.set_index('Date', inplace=True)

    # Rename volumeto column
    df.rename(columns={'volumeto': 'volume'}, inplace=True)

    return df

def create_df_quandl(symbol, api_key):
    ''' This function takes in a symbol of a futures contract to be used
        with the Quandl API as well as the API key, and returns a formatted
        dataframe for processing.

        Args: symbol - a symbol for a continuous futures contract
              api_key - Quandl API key

        Return: df - dataframe for daily price info for symbol
    '''
    # Quandl API call which puts price data into dataframe
    df = quandl.get('SCF/CME_{s}1_FW'.format(s=symbol), authtoken=api_key)

    # Drop open interest column and rename Settle column
    df.drop(['Prev. Day Open Interest'], axis=1, inplace=True)
    df.rename(columns={'Open': 'open',
                      'High': 'high',
                      'Low': 'low',
                      'Settle': 'close',
                      'Volume': 'volume'}, inplace=True)
    return df

def clean_df_crypto(df, volume_thresh=1000000):
    ''' This function takes in a dataframe and a volume threshold and returns a filtered
        dataframe from the first data point that achieves the threshold.  This is written
        to be used specifically with the cryptocurrency dataframes.

        Args: df - dataframe to be filtered on volume
              volume_thresh - min volume to reach before using data in the dataframe

        Return df - the filtered dataframe with only points after the volume threshold is hit
    '''
    # Find start_date and filter df
    start_date = df.index[df.volume > volume_thresh].tolist()[0]
    df = df[start_date:]

    return df

def replace_df_zeros(df):
    ''' This function takes in a dataframe of price information, finds all zero values
        for the 'volume' column and replaces them with the mean volume of the dataset.

        Args: df - dataframe of price information

        Return: df - cleaned dataframe with no zero volume entries
    '''
    df['volume'].replace(0.0, df['volume'].mean(), inplace=True)

    return df

def check_outliers(df):
    ''' This function finds all closing price points that are more than 3 stds away from
        the mean and plots them on a line graph of all the data.  This can be used to see
        if these points are truly outliers.

        Args: df - dataframe to be checked for outliers

        Return: None - shows a graph of the price data series with annotations for outliers
    '''
    # Use a copy of the dataframe
    cpy = df.copy()
    # Create range of values that are more than 3 stds away from mean
    cpy['stds_from_mean'] = ((cpy['close'] - cpy['close'].mean()).apply(abs)) / cpy['close'].std()
    locs_gt_3std = [cpy.index.get_loc(x) for x in cpy.index[cpy['stds_from_mean'] > 3.0]]

    # Plot the price data, highlighting the outliers
    plt.figure(figsize=(15,10))
    plt.plot(cpy.index, cpy.close, linestyle='solid', markevery=locs_gt_3std,
                marker='o', markerfacecolor='r', label='Outliers')

    # Apply title, legend and labels
    plt.title('Closing Prices')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend()
    plt.grid()

    plt.show()

    # Print out description
    print('Number of data points: {}'.format(len(cpy.index)))
    print('Number of outliers: {}'.format(len(locs_gt_3std)))

def generate_df_dict(product_dict, api_key=None):
    ''' This function takes in a dict of product symbols mapped to
        information about the product  and a Quandl API key and returns
        a dict object with the symbols as keys and a dataframe of price
        info as values.

        Args: product_dict - a dict of symbols for products with maps to
                             a list of info
              api_key - Quandl API key

        Return: df_dict - a dictionary of symbols mapped to dataframes
                          of price info
    '''
    df_dict = {}

    # Iterate through list
    for product, info in product_dict.items():
        # Determine what dataframe creator to use
        if info[0] == 1:
            df = create_df_crypto(product)
            df = clean_df_crypto(df)
            df = replace_df_zeros(df)
        if info[0] == 2:
            df = create_df_quandl(product, api_key)
            df = replace_df_zeros(df)

        df_dict[product] = df

    return df_dict

In [3]:
api_key = 'Hv95pPh1xQWzt5DFhxS7'

In [4]:
products = {'CL': [2, 'Crude', 'Energy', 'CME'],
                'HO': [2, 'HeatOil', 'Energy', 'CME'],
                'NG': [2, 'NatGas', 'Energy', 'CME'],
                'GC': [2, 'Gold', 'Metals', 'CME'],
                'SI': [2, 'Silver', 'Metals', 'CME'],
                'AD': [2, 'Aussie', 'Forex', 'CME'],
                'CD': [2, 'Canadien', 'Forex', 'CME'],
                'EC': [2, 'Euro', 'Forex', 'CME'],
                'BP': [2, 'Pound', 'Forex', 'CME'],
                'JY': [2, 'Yen', 'Forex', 'CME'],
                'US': [2, '30-yr', 'Treasuries', 'CME'],
                'C': [2, 'Corn', 'Grains', 'CME'],
                'W': [2, 'Wheat', 'Grains', 'CME'],
                'S': [2, 'Soybeans', 'Grains', 'CME'],
                'ES': [2, 'E-mini', 'Indexes', 'CME'],
                'BTC': [1, 'Bitcoin', 'Cryptocurrency', 'CCAgg'],
                'ETH': [1, 'Ethereum', 'Cryptocurrency', 'CCAgg'],
                'XRP': [1, 'Ripple', 'Cryptocurrency', 'CCAgg'],
                'BCH': [1, 'BitcoinCash', 'Cryptocurrency', 'CCAgg'],
                'LTC': [1, 'Litecoin', 'Cryptocurrency', 'CCAgg'],
                'ADA': [1, 'Cardano', 'Cryptocurrency', 'CCAgg'],
                'NEO': [1, 'Neo', 'Cryptocurrency', 'CCAgg'],
                'XLM': [1, 'Stellar', 'Cryptocurrency', 'CCAgg'],
                'EOS': [1, 'EOS', 'Cryptocurrency', 'CCAgg'],
                'XMR': [1, 'Monero', 'Cryptocurrency', 'CCAgg'],}

In [5]:
df_dict = generate_df_dict(products, api_key)

In [6]:
emini = df_dict['ES']
emini.head()

               open     high      low    close    volume
Date
2005-01-03  1213.50  1221.25  1201.75  1206.25  672360.0
2005-01-04  1206.25  1209.50  1186.75  1191.00  869562.0
2005-01-05  1190.75  1195.00  1182.75  1183.25  855689.0
2005-01-06  1183.25  1193.75  1182.75  1188.25  678414.0
2005-01-07  1188.50  1194.50  1183.50  1186.25  766197.0

In [7]:
def vol_bo(row, direction):
    ''' This is a helper function to use in volume breakout column creation.  It takes
        in a row of a dataframe and a direction of trade, and returns 1 if a breakout
        has occured, 0 if not.

        Args: row - row of a dataframe
              direction - 'long' or 'short'

        Return: 1 if volume breakout occured, 0 if not
    '''
    if row['volume'] > (2 * row['20day_ave_vol']):
        if (direction == 'long') and (row['close_gt_prev_h'] > 0.0):
            return 1
        elif (direction == 'short') and (row['close_lt_prev_l'] < 0.0):
            return 1
        else:
            return 0

def range_bo(row, direction):
    ''' This is a helper function to use in range breakout column creation.  It takes
        in a row of a dataframe and a direction of trade, and returns 1 if a breakout
        has occured, 0 if not.

        Args: row - row of a dataframe
              direction - 'long' or 'short'

        Return: 1 if volume breakout occured, 0 if not
    '''
    if direction == 'long':
        if row['high'] > row['20day_high']:
            return 1
        else:
            return 0
    if direction == 'short':
        if row['low'] < row['20day_low']:
            return 1
        else:
            return 0

def ma_signal(row, ma, direction):
    ''' This is a helper function to use in all moving average columns creation.  It takes
        in a row of a dataframe, a length of time and a direction of trade, and returns
        1 if a breakout has occured, 0 if not.

        Args: row - row of a dataframe
              ma - length of time for moving average
              direction - 'long' or 'short'

        Return: 1 if volume breakout occured, 0 if not
    '''
    if direction == 'long':
        if row['close'] > row['ma{}'.format(ma)]:
            return 1
        else:
            return 0
    if direction == 'short':
        if row['close'] < row['ma{}'.format(ma)]:
            return 1
        else:
            return 0

def bb_signal(row, direction):
    ''' This is a helper function to use in all bollinger band column creation.  It takes
        in a row of a dataframe and a direction of trade, and returns 1 if a breakout
        has occured, 0 if not.

        Args: row - row of a dataframe
              direction - 'long' or 'short'

        Return: 1 if volume breakout occured, 0 if not
    '''
    if direction == 'long':
        if row['low'] < row['bb_low']:
            return 1
        else:
            return 0
    if direction == 'short':
        if row['high'] > row['bb_high']:
            return 1
        else:
            return 0

def add_all_indicators(df):
    ''' This function takes in a cleaned dataframe of price information and uses
        the helper functions to add all relevant indicators as columns
        to the dataframe.

        Args: df - cleaned dataframe of price information

        Return: df - cleaned dataframe with added columns for all indicators
    '''
    # All columns for 20day volume breakout indicator
    df['20day_ave_vol'] = df.volume.rolling(window=20, center=False).mean().shift(1)
    df['close_gt_prev_h'] = df['close'] - df['high'].shift(1)
    df['close_lt_prev_l'] = df['close'] - df['low'].shift(1)
    df['vol_bo_long'] = df.apply(lambda row: vol_bo(row, direction='long'), axis=1)
    df['vol_bo_short'] = df.apply(lambda row: vol_bo(row, direction='short'), axis=1)
    df['vol_bo_long'].fillna(value=0, inplace=True)
    df['vol_bo_short'].fillna(value=0, inplace=True)

    # All columns for 20day range breakout indicator
    df['20day_high'] = df.high.rolling(window=20, center=False).max().shift(1)
    df['20day_low'] = df.low.rolling(window=20, center=False).min().shift(1)
    df['range_bo_long'] = df.apply(lambda row: range_bo(row, direction='long'), axis=1)
    df['range_bo_short'] = df.apply(lambda row: range_bo(row, direction='short'), axis=1)

    # All columns for moving average indicators
    df['ma20'] = df['close'].rolling(window=20, center=False).mean()
    df['ma50'] = df['close'].rolling(window=50, center=False).mean()
    df['ma100'] = df['close'].rolling(window=100, center=False).mean()
    df['ma20_long'] = df.apply(lambda row: ma_signal(row, ma=20, direction='long'), axis=1)
    df['ma20_short'] = df.apply(lambda row: ma_signal(row, ma=20, direction='short'), axis=1)
    df['ma50_long'] = df.apply(lambda row: ma_signal(row, ma=50, direction='long'), axis=1)
    df['ma50_short'] = df.apply(lambda row: ma_signal(row, ma=50, direction='short'), axis=1)
    df['ma100_long'] = df.apply(lambda row: ma_signal(row, ma=100, direction='long'), axis=1)
    df['ma100_short'] = df.apply(lambda row: ma_signal(row, ma=100, direction='short'), axis=1)

    # All columns for bollinger band indicators
    df['bb_high'] = df['ma20'] + (2 * df['close'].rolling(window=20, center=False).std())
    df['bb_low'] = df['ma20'] - (2 * df['close'].rolling(window=20, center=False).std())
    df['bb_long'] = df.apply(lambda row: bb_signal(row, direction='long'), axis=1)
    df['bb_short'] = df.apply(lambda row: bb_signal(row, direction='short'), axis=1)

    # All columns for percentage change for timeframe into the future
    df['pct_change_1day'] = df['close'].pct_change()
    df['pct_change_5day'] = df['close'].pct_change(periods=5)
    df['pct_change_10day'] = df['close'].pct_change(periods=10)
    df['pct_change_20day'] = df['close'].pct_change(periods=20)

    return df

In [8]:
emini = add_all_indicators(emini)
emini.tail()

,open,high,low,close,volume,20day_ave_vol,close_gt_prev_h,close_lt_prev_l,vol_bo_long,vol_bo_short,...,ma100_long,ma100_short,bb_high,bb_low,bb_long,bb_short,pct_change_1day,pct_change_5day,pct_change_10day,pct_change_20day
Date,,,,,,,,,,,,,,,,,,,,,
2014-12-24,2078.75,2083.50,2077.00,2078.75,235054.0,1263141.32,-5.75,7.25,0.0,0.0,...,1,0,2111.738883,1976.291117,0,0,-0.000120,0.035105,0.029339,0.006805
2014-12-26,2078.75,2088.75,2078.50,2084.25,614078.0,1245425.85,0.75,7.25,0.0,0.0,...,1,0,2114.146410,1975.518590,0,0,0.002646,0.011772,0.029768,0.007907
2014-12-29,2086.00,2088.75,2076.00,2085.75,636306.0,1261111.33,-3.00,7.25,0.0,0.0,...,1,0,2117.484882,1974.690118,0,0,0.000720,0.009071,0.047852,0.012181
2014-12-30,2087.50,2088.50,2073.00,2076.75,716610.0,1284785.30,-12.00,0.75,0.0,0.0,...,1,0,2120.430628,1975.069372,0,0,-0.004315,0.002051,0.047145,0.016271
2014-12-31,2076.25,2082.75,2050.75,2052.50,835262.0,1319991.85,-36.00,-20.50,0.0,0.0,...,1,0,2119.972587,1974.902413,0,0,-0.011677,-0.012747,0.044529,-0.003036

## Begin the summary on emini as an example

In [9]:
# Get general info
emini.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2571 entries, 2005-01-03 to 2014-12-31
Data columns (total 31 columns):
open                2571 non-null float64
high                2571 non-null float64
low                 2571 non-null float64
close               2571 non-null float64
volume              2571 non-null float64
20day_ave_vol       2551 non-null float64
close_gt_prev_h     2570 non-null float64
close_lt_prev_l     2570 non-null float64
vol_bo_long         2571 non-null float64
vol_bo_short        2571 non-null float64
20day_high          2551 non-null float64
20day_low           2551 non-null float64
range_bo_long       2571 non-null int64
range_bo_short      2571 non-null int64
ma20                2552 non-null float64
ma50                2522 non-null float64
ma100               2472 non-null float64
ma20_long           2571 non-null int64
ma20_short          2571 non-null int64
ma50_long           2571 non-null int64
ma50_short          2571 non-null int64
ma100_long          2571 non-null int64
ma100_short         2571 non-null int64
bb_high             2552 non-null float64
bb_low              2552 non-null float64
bb_long             2571 non-null int64
bb_short            2571 non-null int64
pct_change_1day     2570 non-null float64
pct_change_5day     2566 non-null float64
pct_change_10day    2561 non-null float64
pct_change_20day    2551 non-null float64
dtypes: float64(21), int64(10)
memory usage: 642.8 KB

Notice that it is all quantitative data we are dealing with.  Can check out the stats as follows

In [10]:
emini.describe()

/Users/Frank/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py:4274: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

,open,high,low,close,volume,20day_ave_vol,close_gt_prev_h,close_lt_prev_l,vol_bo_long,vol_bo_short,...,ma100_long,ma100_short,bb_high,bb_low,bb_long,bb_short,pct_change_1day,pct_change_5day,pct_change_10day,pct_change_20day
count,2571.000000,2571.000000,2571.000000,2571.000000,2.571000e+03,2.551000e+03,2570.000000,2570.000000,2571.000000,2571.000000,...,2571.000000,2571.000000,2552.000000,2552.000000,2571.00000,2571.000000,2570.000000,2566.000000,2561.000000,2551.000000
mean,1349.318300,1358.939129,1339.244963,1349.722170,1.498132e+06,1.501091e+06,-8.879494,10.809883,0.013224,0.022948,...,0.672501,0.288993,1389.829110,1305.584076,0.12252,0.094127,0.000290,0.001411,0.002746,0.005432
std,275.854506,274.908956,277.173280,276.181157,9.366424e+05,6.347744e+05,17.593375,17.346529,0.114257,0.149768,...,0.469392,0.453383,270.667714,276.780754,0.32795,0.292062,0.012870,0.025448,0.033636,0.046391
min,671.250000,691.750000,662.750000,673.000000,1.000000e+00,3.953674e+05,-163.750000,-71.000000,0.000000,0.000000,...,0.000000,0.000000,805.009623,647.133863,0.00000,0.000000,-0.098778,-0.196030,-0.266365,-0.292014
25%,1189.750000,1197.050000,1180.500000,1190.000000,8.374098e+05,NaN,NaN,NaN,0.000000,0.000000,...,0.000000,0.000000,NaN,NaN,0.00000,0.000000,NaN,NaN,NaN,NaN
50%,1313.000000,1321.000000,1304.100000,1312.750000,1.498761e+06,NaN,NaN,NaN,0.000000,0.000000,...,1.000000,0.000000,NaN,NaN,0.00000,0.000000,NaN,NaN,NaN,NaN
75%,1472.575000,1482.875000,1460.000000,1473.525000,2.032430e+06,NaN,NaN,NaN,0.000000,0.000000,...,1.000000,1.000000,NaN,NaN,0.00000,0.000000,NaN,NaN,NaN,NaN
max,2087.500000,2088.750000,2078.500000,2085.750000,6.285917e+06,3.833194e+06,73.750000,179.750000,1.000000,1.000000,...,1.000000,1.000000,2120.430628,2028.942131,1.00000,1.000000,0.141134,0.188039,0.215453,0.234027

In [27]:
date_range = def vol_bo(row, direction):
    ''' This is a helper function to use in volume breakout column creation.  It takes
        in a row of a dataframe and a direction of trade, and returns 1 if a breakout
        has occured, 0 if not.

        Args: row - row of a dataframe
              direction - 'long' or 'short'

        Return: 1 if volume breakout occured, 0 if not
    '''
    if row['volume'] > (2 * row['20day_ave_vol']):
        if (direction == 'long') and (row['close_gt_prev_h'] > 0.0):
            return 1
        elif (direction == 'short') and (row['close_lt_prev_l'] < 0.0):
            return 1
        else:
            return 0

def range_bo(row, direction):
    ''' This is a helper function to use in range breakout column creation.  It takes
        in a row of a dataframe and a direction of trade, and returns 1 if a breakout
        has occured, 0 if not.

        Args: row - row of a dataframe
              direction - 'long' or 'short'

        Return: 1 if volume breakout occured, 0 if not
    '''
    if direction == 'long':
        if row['high'] > row['20day_high']:
            return 1
        else:
            return 0
    if direction == 'short':
        if row['low'] < row['20day_low']:
            return 1
        else:
            return 0

def ma_signal(row, ma, direction):
    ''' This is a helper function to use in all moving average columns creation.  It takes
        in a row of a dataframe, a length of time and a direction of trade, and returns
        1 if a breakout has occured, 0 if not.

        Args: row - row of a dataframe
              ma - length of time for moving average
              direction - 'long' or 'short'

        Return: 1 if volume breakout occured, 0 if not
    '''
    if direction == 'long':
        if row['close'] > row['ma{}'.format(ma)]:
            return 1
        else:
            return 0
    if direction == 'short':
        if row['close'] < row['ma{}'.format(ma)]:
            return 1
        else:
            return 0

def bb_signal(row, direction):
    ''' This is a helper function to use in all bollinger band column creation.  It takes
        in a row of a dataframe and a direction of trade, and returns 1 if a breakout
        has occured, 0 if not.

        Args: row - row of a dataframe
              direction - 'long' or 'short'

        Return: 1 if volume breakout occured, 0 if not
    '''
    if direction == 'long':
        if row['low'] < row['bb_low']:
            return 1
        else:
            return 0
    if direction == 'short':
        if row['high'] > row['bb_high']:
            return 1
        else:
            return 0

def add_all_indicators(df):
    ''' This function takes in a cleaned dataframe of price information and uses
        the helper functions to add all relevant indicators as columns
        to the dataframe.

        Args: df - cleaned dataframe of price information

        Return: df - cleaned dataframe with added columns for all indicators
    '''
    # All columns for 20day volume breakout indicator
    df['20day_ave_vol'] = df.volume.rolling(window=20, center=False).mean().shift(1)
    df['close_gt_prev_h'] = df['close'] - df['high'].shift(1)
    df['close_lt_prev_l'] = df['close'] - df['low'].shift(1)
    df['vol_bo_long'] = df.apply(lambda row: vol_bo(row, direction='long'), axis=1)
    df['vol_bo_short'] = df.apply(lambda row: vol_bo(row, direction='short'), axis=1)
    df['vol_bo_long'].fillna(value=0, inplace=True)
    df['vol_bo_short'].fillna(value=0, inplace=True)

    # All columns for 20day range breakout indicator
    df['20day_high'] = df.high.rolling(window=20, center=False).max().shift(1)
    df['20day_low'] = df.low.rolling(window=20, center=False).min().shift(1)
    df['range_bo_long'] = df.apply(lambda row: range_bo(row, direction='long'), axis=1)
    df['range_bo_short'] = df.apply(lambda row: range_bo(row, direction='short'), axis=1)

    # All columns for moving average indicators
    df['ma20'] = df['close'].rolling(window=20, center=False).mean()
    df['ma50'] = df['close'].rolling(window=50, center=False).mean()
    df['ma100'] = df['close'].rolling(window=100, center=False).mean()
    df['ma20_long'] = df.apply(lambda row: ma_signal(row, ma=20, direction='long'), axis=1)
    df['ma20_short'] = df.apply(lambda row: ma_signal(row, ma=20, direction='short'), axis=1)
    df['ma50_long'] = df.apply(lambda row: ma_signal(row, ma=50, direction='long'), axis=1)
    df['ma50_short'] = df.apply(lambda row: ma_signal(row, ma=50, direction='short'), axis=1)
    df['ma100_long'] = df.apply(lambda row: ma_signal(row, ma=100, direction='long'), axis=1)
    df['ma100_short'] = df.apply(lambda row: ma_signal(row, ma=100, direction='short'), axis=1)

    # All columns for bollinger band indicators
    df['bb_high'] = df['ma20'] + (2 * df['close'].rolling(window=20, center=False).std())
    df['bb_low'] = df['ma20'] - (2 * df['close'].rolling(window=20, center=False).std())
    df['bb_long'] = df.apply(lambda row: bb_signal(row, direction='long'), axis=1)
    df['bb_short'] = df.apply(lambda row: bb_signal(row, direction='short'), axis=1)

    # All columns for percentage change for timeframe into the future
    df['pct_change_1day'] = df['close'].pct_change()
    df['pct_change_5day'] = df['close'].pct_change(periods=5)
    df['pct_change_10day'] = df['close'].pct_change(periods=10)
    df['pct_change_20day'] = df['close'].pct_change(periods=20)

    return df

This dataset is comprised of 3649 days
from 01-03-05 to 12-31-14

In [30]:
# Get the range, number of days, data points, start date and end date
date_range = (emini.index[-1] - emini.index[0]).days
start_date = emini.index[0].strftime('%m-%d-%y')
end_date = emini.index[-1].strftime('%m-%d-%y')
data_points = len(emini.close)

print('This dataset is comprised of {} calendar days'.format(date_range))
print('from {} to {}'.format(start_date, end_date))
print('with {} total daily data points.'.format(data_points))

This dataset is comprised of 3649 calendar days
from 01-03-05 to 12-31-14
with 2571 total daily data points.

In [34]:
emini_monthly = emini.groupby([(emini.index.year), (emini.index.month)])

In [35]:
emini_monthly.head(15)

,open,high,low,close,volume,20day_ave_vol,close_gt_prev_h,close_lt_prev_l,vol_bo_long,vol_bo_short,...,ma100_long,ma100_short,bb_high,bb_low,bb_long,bb_short,pct_change_1day,pct_change_5day,pct_change_10day,pct_change_20day
Date,,,,,,,,,,,,,,,,,,,,,
2005-01-03,1213.50,1221.25,1201.75,1206.25,672360.0,NaN,NaN,NaN,0.0,0.0,...,0,0,NaN,NaN,0,0,NaN,NaN,NaN,NaN
2005-01-04,1206.25,1209.50,1186.75,1191.00,869562.0,NaN,-30.25,-10.75,0.0,0.0,...,0,0,NaN,NaN,0,0,-0.012642,NaN,NaN,NaN
2005-01-05,1190.75,1195.00,1182.75,1183.25,855689.0,NaN,-26.25,-3.50,0.0,0.0,...,0,0,NaN,NaN,0,0,-0.006507,NaN,NaN,NaN
2005-01-06,1183.25,1193.75,1182.75,1188.25,678414.0,NaN,-6.75,5.50,0.0,0.0,...,0,0,NaN,NaN,0,0,0.004226,NaN,NaN,NaN
2005-01-07,1188.50,1194.50,1183.50,1186.25,766197.0,NaN,-7.50,3.50,0.0,0.0,...,0,0,NaN,NaN,0,0,-0.001683,NaN,NaN,NaN
2005-01-10,1187.00,1196.75,1185.25,1191.75,727775.0,NaN,-2.75,8.25,0.0,0.0,...,0,0,NaN,NaN,0,0,0.004636,-0.012021,NaN,NaN
2005-01-11,1191.25,1192.75,1181.75,1184.00,759233.0,NaN,-12.75,-1.25,0.0,0.0,...,0,0,NaN,NaN,0,0,-0.006503,-0.005877,NaN,NaN
2005-01-12,1186.00,1189.75,1176.75,1187.50,948455.0,NaN,-5.25,5.75,0.0,0.0,...,0,0,NaN,NaN,0,0,0.002956,0.003592,NaN,NaN
2005-01-13,1187.75,1190.25,1176.25,1178.00,727580.0,NaN,-11.75,1.25,0.0,0.0,...,0,0,NaN,NaN,0,0,-0.008000,-0.008626,NaN,NaN
2005-01-14,1178.25,1186.75,1176.75,1183.75,518753.0,NaN,-6.50,7.50,0.0,0.0,...,0,0,NaN,NaN,0,0,0.004881,-0.002107,NaN,NaN
2005-01-17,1185.00,1187.00,1184.75,1186.00,518753.0,NaN,-0.75,9.25,0.0,0.0,...,0,0,NaN,NaN,0,0,0.001901,-0.004825,-0.016788,NaN
2005-01-18,1185.00,1197.75,1180.50,1195.75,777663.0,NaN,8.75,11.00,0.0,0.0,...,0,0,NaN,NaN,0,0,0.008221,0.009924,0.003988,NaN
2005-01-19,1196.00,1197.25,1183.25,1183.50,730230.0,NaN,-14.25,3.00,0.0,0.0,...,0,0,NaN,NaN,0,0,-0.010245,-0.003368,0.000211,NaN
2005-01-20,1181.50,1183.00,1174.00,1176.50,929786.0,NaN,-20.75,-6.75,0.0,0.0,...,0,0,NaN,NaN,0,0,-0.005915,-0.001273,-0.009888,NaN
2005-01-21,1177.25,1180.75,1167.25,1168.50,900208.0,NaN,-14.50,-5.50,0.0,0.0,...,0,0,NaN,NaN,0,0,-0.006800,-0.012883,-0.014963,NaN
2005-02-01,1181.75,1191.00,1179.50,1189.25,651757.0,764339.10,6.25,12.50,0.0,0.0,...,0,0,1197.323487,1164.951513,0,0,0.006347,0.016670,-0.005436,-0.001469
2005-02-02,1189.75,1196.00,1189.00,1193.25,587228.0,753448.85,2.25,13.75,0.0,0.0,...,0,0,1198.692731,1164.582269,0,0,0.003363,0.017047,0.008238,0.008451
2005-02-03,1192.25,1193.50,1185.75,1189.50,569604.0,740025.80,-6.50,0.50,0.0,0.0,...,0,0,1198.866062,1164.533938,0,0,-0.003143,0.012556,0.011050,0.001052
2005-02-04,1189.75,1204.50,1188.25,1202.00,654585.0,734585.30,8.50,16.25,0.0,0.0,...,0,0,1201.838466,1163.136534,0,1,0.010509,0.023196,0.028669,0.013277
2005-02-07,1202.75,1205.00,1199.50,1200.75,441330.0,729004.70,-3.75,12.50,0.0,0.0,...,0,0,1203.571449,1162.303551,0,1,-0.001040,0.016078,0.029582,0.007552
2005-02-08,1201.00,1206.25,1200.00,1202.25,458474.0,714682.45,-2.75,2.75,0.0,0.0,...,0,0,1206.222681,1161.477319,0,1,0.001249,0.010931,0.027784,0.015414
2005-02-09,1201.75,1204.50,1191.75,1193.00,674518.0,699644.50,-13.25,-7.00,0.0,0.0,...,0,0,1206.819481,1161.430519,0,0,-0.007694,-0.000210,0.016834,0.004632
2005-02-10,1192.50,1199.50,1191.75,1196.50,624507.0,685947.65,-8.00,4.75,0.0,0.0,...,0,0,1208.196899,1161.903101,0,0,0.002934,0.005885,0.018515,0.015705
2005-02-11,1196.75,1210.00,1193.75,1207.00,807304.0,680794.00,7.50,15.25,0.0,0.0,...,0,0,1211.335500,1161.089500,0,0,0.008776,0.004160,0.027453,0.019641
2005-02-14,1207.75,1208.50,1204.00,1206.25,417612.0,695221.55,-3.75,12.50,0.0,0.0,...,0,0,1213.896441,1160.553559,0,0,-0.000621,0.004580,0.020732,0.017074
2005-02-15,1206.25,1213.50,1205.50,1210.75,677146.0,690164.50,2.25,6.75,0.0,0.0,...,0,0,1216.439151,1159.510849,0,0,0.003731,0.007070,0.018079,0.012544
2005-02-16,1210.50,1213.50,1203.50,1210.50,659402.0,685138.65,-3.00,5.00,0.0,0.0,...,0,0,1219.410448,1159.239552,0,0,-0.000206,0.014669,0.014456,0.022814
2005-02-17,1210.75,1212.00,1200.75,1201.00,807624.0,681597.25,-12.50,-2.50,0.0,0.0,...,0,0,1220.431168,1160.668832,0,0,-0.007848,0.003761,0.009668,0.020824
2005-02-18,1201.25,1203.75,1197.50,1202.25,600297.0,675489.15,-9.75,1.50,0.0,0.0,...,0,0,1220.651486,1163.823514,0,0,0.001041,-0.003935,0.000208,0.028883
2005-02-22,1203.00,1203.25,1184.00,1184.75,949859.0,660493.60,-19.00,-12.75,0.0,0.0,...,0,0,1219.111983,1167.213017,0,0,-0.014556,-0.017824,-0.013325,0.015863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-11-03,2011.25,2019.25,2007.00,2011.00,1358108.0,2376203.65,-5.75,24.25,0.0,0.0,...,1,0,2032.325078,1829.324922,0,0,-0.000249,0.027593,0.058421,0.028119
2014-11-04,2010.50,2013.75,1995.25,2005.50,1518682.0,2357744.60,-13.75,-1.50,0.0,0.0,...,1,0,2041.523834,1827.876166,0,0,-0.002735,0.012879,0.034830,0.040197
2014-11-05,2006.25,2020.50,2003.75,2018.75,1568956.0,2326003.10,5.00,23.50,0.0,0.0,...,1,0,2050.290106,1824.809894,0,0,0.006607,0.023577,0.048701,0.029056
2014-11-06,2018.50,2029.25,2010.75,2028.00,1433396.0,2278647.60,7.50,24.25,0.0,0.0,...,1,0,2062.231828,1823.168172,0,0,0.004582,0.019864,0.042138,0.053506
2014-11-07,2027.25,2033.50,2020.50,2026.00,1282333.0,2195731.00,-3.25,15.25,0.0,0.0,...,1,0,2072.054639,1826.520361,0,0,-0.000986,0.007209,0.033805,0.069553
2014-11-10,2025.75,2035.00,2021.00,2034.00,957940.0,2106472.85,0.50,13.50,0.0,0.0,...,1,0,2079.391248,1836.033752,0,0,0.003949,0.011437,0.039346,0.090324
2014-11-11,2033.75,2039.00,2031.00,2036.50,779077.0,2007264.00,1.50,15.50,0.0,0.0,...,1,0,2085.750604,1845.849396,0,0,0.001229,0.015457,0.028535,0.086278
2014-11-12,2036.50,2037.25,2026.75,2036.00,1082154.0,1890649.90,-3.00,5.00,0.0,0.0,...,1,0,2085.102632,1865.422368,0,0,-0.000246,0.008545,0.032323,0.102477
2014-11-13,2034.75,2043.75,2026.75,2034.00,1541378.0,1711808.95,-3.25,7.25,0.0,0.0,...,1,0,2080.144134,1888.730866,0,0,-0.000982,0.002959,0.022882,0.099162
2014-11-14,2033.00,2039.75,2032.00,2038.00,1045649.0,1620993.30,-5.75,11.25,0.0,0.0,...,1,0,2077.444982,1907.130018,0,0,0.001967,0.005923,0.013174,0.083466
2014-11-17,2038.50,2040.50,2025.25,2039.75,1058349.0,1544997.65,0.00,7.75,0.0,0.0,...,1,0,2074.954709,1923.595291,0,0,0.000859,0.002827,0.014296,0.073553
2014-11-18,2039.25,2054.00,2035.75,2048.50,1140878.0,1515421.70,8.00,23.25,0.0,0.0,...,1,0,2077.728516,1931.871484,0,0,0.004290,0.005892,0.021441,0.057018
2014-11-19,2048.75,2050.50,2037.75,2047.25,1188389.0,1460556.55,-6.75,11.50,0.0,0.0,...,1,0,2075.719760,1946.105240,0,0,-0.000610,0.005526,0.014118,0.063506
2014-11-20,2047.00,2052.75,2035.25,2052.00,1125939.0,1419330.25,1.50,14.25,0.0,0.0,...,1,0,2075.794658,1956.630342,0,0,0.002320,0.008850,0.011834,0.054471
2014-11-21,2052.25,2072.25,2049.75,2061.75,1630436.0,1374887.65,9.00,26.50,0.0,0.0,...,1,0,2077.933324,1964.691676,0,0,0.004751,0.011654,0.017646,0.052047
2014-12-01,2056.75,2057.00,2041.25,2043.50,12479.0,1115781.56,-25.25,-14.60,0.0,0.0,...,1,0,2076.987582,2004.992418,0,0,-0.008323,-0.008852,0.002699,0.015909
2014-12-02,2044.25,2061.00,2044.00,2058.75,15251.0,1020230.96,1.75,17.50,0.0,0.0,...,1,0,2077.272655,2009.482345,0,0,0.007463,-0.003533,0.009315,0.023744
2014-12-03,2059.50,2068.50,2056.00,2065.50,28316.0,953088.11,4.50,21.50,0.0,0.0,...,1,0,2076.576445,2016.178555,0,0,0.003279,0.000387,0.008299,0.029918
2014-12-04,2066.00,2070.00,2054.00,2064.50,30889.0,878569.81,-4.00,8.50,0.0,0.0,...,1,0,2076.920900,2020.409100,0,0,-0.000484,-0.001644,0.008426,0.022663
2014-12-05,2064.00,2071.75,2061.50,2069.00,32452.0,801666.46,-1.00,15.00,0.0,0.0,...,1,0,2078.605011,2022.824989,0,0,0.002180,0.004052,0.008285,0.020217
2014-12-08,2068.75,2070.50,2046.75,2052.25,61082.0,731619.26,-19.50,-9.25,0.0,0.0,...,1,0,2077.375073,2026.679927,0,0,-0.008096,0.004282,-0.004608,0.012957
2014-12-09,2053.25,2055.00,2026.25,2050.50,149696.0,670556.71,-20.00,3.75,0.0,0.0,...,1,0,2076.762869,2028.942131,1,0,-0.000853,-0.004007,-0.007526,0.008112
2014-12-10,2050.75,2053.00,2016.50,2019.50,307179.0,630144.51,-35.50,-6.75,0.0,0.0,...,1,0,2079.325663,2024.679337,1,0,-0.015118,-0.022271,-0.021892,-0.008348
2014-12-11,2019.75,2049.50,2017.00,2024.00,873587.0,606549.61,-29.00,7.50,0.0,0.0,...,1,0,2080.663566,2022.141434,1,0,0.002228,-0.019617,-0.021229,-0.005894
2014-12-12,2022.50,2025.50,1989.75,1990.50,2461714.0,596121.26,-59.00,-26.50,0.0,1.0,...,1,0,2088.640702,2009.814298,1,0,-0.016551,-0.037941,-0.034043,-0.021386
2014-12-15,1990.50,2012.25,1974.50,1983.25,5619572.0,642138.06,-42.25,-6.50,0.0,1.0,...,1,0,2095.599433,1997.380567,1,0,-0.003642,-0.033622,-0.029484,-0.026865
2014-12-16,1984.50,2011.25,1961.50,1965.00,3345368.0,870834.21,-47.25,-9.50,0.0,1.0,...,0,1,2103.919334,1981.585666,1,0,-0.009202,-0.041697,-0.045537,-0.036647
2014-12-17,1966.75,2011.00,1966.00,2008.25,5528322.0,985185.16,-3.00,46.75,0.0,0.0,...,1,0,2103.731976,1977.748024,1,0,0.022010,-0.005571,-0.027717,-0.019649
2014-12-18,2008.00,2062.75,2004.50,2060.00,2353440.0,1204557.36,49.00,94.00,0.0,0.0,...,1,0,2104.902692,1977.852308,0,0,0.025769,0.017787,-0.002180,0.006228
2014-12-19,2060.25,2076.25,2056.50,2067.00,1762169.0,1262809.91,4.25,62.50,0.0,0.0,...,1,0,2106.528893,1977.726107,0,0,0.003398,0.038433,-0.000967,0.007310

In [37]:
emini['vol_bo_long'].value_counts()

0.0    2537
1.0      34
Name: vol_bo_long, dtype: int64

In [38]:
emini_signals = emini[['vol_bo_long', 'vol_bo_short', 'range_bo_long', 'range_bo_short',
                       'ma20_long', 'ma20_short', 'ma50_long', 'ma50_short', 'ma100_long',
                       'ma100_short', 'bb_long', 'bb_short']]

In [39]:
emini_signals.describe()

,vol_bo_long,vol_bo_short,range_bo_long,range_bo_short,ma20_long,ma20_short,ma50_long,ma50_short,ma100_long,ma100_short,bb_long,bb_short
count,2571.000000,2571.000000,2571.000000,2571.000000,2571.000000,2571.000000,2571.000000,2571.000000,2571.000000,2571.000000,2571.00000,2571.000000
mean,0.013224,0.022948,0.208479,0.106573,0.630494,0.362116,0.644107,0.336834,0.672501,0.288993,0.12252,0.094127
std,0.114257,0.149768,0.406300,0.308630,0.482765,0.480706,0.478876,0.472720,0.469392,0.453383,0.32795,0.292062
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.00000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.00000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000

In [48]:
# Get a count of each strategy signals
for signal in emini_signals.columns:
    print(signal, emini_signals[signal].value_counts()[1])

vol_bo_long 34
vol_bo_short 59
range_bo_long 536
range_bo_short 274
ma20_long 1621
ma20_short 931
ma50_long 1656
ma50_short 866
ma100_long 1729
ma100_short 743
bb_long 315
bb_short 242

In [50]:
cpy = emini.copy()

In [54]:
# 20day historical vol column added
cpy['20day_hist_vol'] = math.sqrt(252) * cpy['pct_change_1day'].rolling(window=20, center=False).std()

In [56]:
cpy.tail()

,open,high,low,close,volume,20day_ave_vol,close_gt_prev_h,close_lt_prev_l,vol_bo_long,vol_bo_short,...,ma100_short,bb_high,bb_low,bb_long,bb_short,pct_change_1day,pct_change_5day,pct_change_10day,pct_change_20day,20day_hist_vol
Date,,,,,,,,,,,,,,,,,,,,,
2014-12-24,2078.75,2083.50,2077.00,2078.75,235054.0,1263141.32,-5.75,7.25,0.0,0.0,...,0,2111.738883,1976.291117,0,0,-0.000120,0.035105,0.029339,0.006805,0.162910
2014-12-26,2078.75,2088.75,2078.50,2084.25,614078.0,1245425.85,0.75,7.25,0.0,0.0,...,0,2114.146410,1975.518590,0,0,0.002646,0.011772,0.029768,0.007907,0.163060
2014-12-29,2086.00,2088.75,2076.00,2085.75,636306.0,1261111.33,-3.00,7.25,0.0,0.0,...,0,2117.484882,1974.690118,0,0,0.000720,0.009071,0.047852,0.012181,0.162391
2014-12-30,2087.50,2088.50,2073.00,2076.75,716610.0,1284785.30,-12.00,0.75,0.0,0.0,...,0,2120.430628,1975.069372,0,0,-0.004315,0.002051,0.047145,0.016271,0.160059
2014-12-31,2076.25,2082.75,2050.75,2052.50,835262.0,1319991.85,-36.00,-20.50,0.0,0.0,...,0,2119.972587,1974.902413,0,0,-0.011677,-0.012747,0.044529,-0.003036,0.163951

In [57]:
# Monthly historical vol calculation
montly_hist_vol = cpy['20day_hist_vol'].groupby([cpy.index.year, cpy.index.month]).mean()

In [58]:
montly_hist_vol.head()

2005  1    0.094902
      2    0.089545
      3    0.108178
      4    0.118074
      5    0.132141
Name: 20day_hist_vol, dtype: float64

In [60]:
montly_hist_vol

2005  1     0.094902
      2     0.089545
      3     0.108178
      4     0.118074
      5     0.132141
      6     0.076254
      7     0.090499
      8     0.083110
      9     0.092900
      10    0.114618
      11    0.116155
      12    0.073175
2006  1     0.094255
      2     0.098750
      3     0.080566
      4     0.081400
      5     0.106914
      6     0.153238
      7     0.136450
      8     0.098657
      9     0.072141
      10    0.066180
      11    0.068212
      12    0.077117
2007  1     0.068175
      2     0.081534
      3     0.174319
      4     0.086962
      5     0.079420
      6     0.126212
              ...
2012  7     0.168720
      8     0.128110
      9     0.101975
      10    0.108886
      11    0.156834
      12    0.105047
2013  1     0.151412
      2     0.091943
      3     0.111889
      4     0.120372
      5     0.115221
      6     0.137190
      7     0.123524
      8     0.082827
      9     0.104863
      10    0.123907
      11    0.093739
      12    0.091076
2014  1     0.101547
      2     0.153650
      3     0.103110
      4     0.124223
      5     0.088603
      6     0.067137
      7     0.068489
      8     0.107291
      9     0.064445
      10    0.165554
      11    0.111523
      12    0.112031
Name: 20day_hist_vol, dtype: float64